#!/bin/sh
echo "Install go program for multiple OS and multiple architectures"
export SOURCE_DIR="."
export TARGET_DIR="."
# source for the envs- https://golang.org/doc/install/source#environment
declare -d envs
envs["aix"]="ppc64"
envs["android"]="386"
envs["android"]="amd64"
envs["android"]="arm"
envs["android"]="arm64"
envs["darwin"]="386"
envs["darwin"]="amd64"
envs["darwin"]="arm"
envs["darwin"]="arm64"
envs["dragonfly"]="amd64"
envs["freebsd"]="386"
envs["freebsd"]="amd64"
envs["freebsd"]="arm"
envs["illumos"]="amd64"
envs["js"]="wasm"
envs["linux"]="386"
envs["linux"]="amd64"
envs["linux"]="arm"
envs["linux"]="arm64"
envs["linux"]="ppc64"
envs["linux"]="ppc64le"
envs["linux"]="mips"
envs["linux"]="mipsle"
envs["linux"]="mips64"
envs["linux"]="mips64le"
envs["linux"]="s390x"
envs["netbsd"]="386"
envs["netbsd"]="amd64"
envs["netbsd"]="arm"
envs["openbsd"]="386"
envs["openbsd"]="amd64"
envs["openbsd"]="arm"
envs["openbsd"]="arm64"
envs["plan9"]="386"
envs["plan9"]="amd64"
envs["plan9"]="arm"
envs["solaris"]="amd64"
envs["windows"]="386"
envs["windows"]="amd64"
for key in "${!envs[@]}"
do
	echo "key: $i"
	echo "value: ${envs[$i]}"
done				
